# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

services:
  nginx: 'supportusw-docker.jfrog.io/nginx:1.10.0'

steps:
- task: JFrog.jfrog-artifactory-vsts-extension.artifactory-docker.ArtifactoryDocker@1
  displayName: 'Artifactory Docker pull'
  inputs:
    command: pull
    artifactoryService: Support
    sourceRepo: docker
    imageName: 'supportusw-docker.jfrog.io/nginx:1.10.0'
