resources:
  containers:
  - container: my_container
    image: ubuntu:16.04
  - container: nginx
    image: nginx
  - container: redis
    image: redis
pool:
  vmImage: 'ubuntu-16.04'
container: my_container
services:
  nginx: nginx
  redis: redis
steps:
- task: ArtifactoryDocker@1
  inputs:
    command: 'pull'
    artifactoryService: 'supportusw'
    sourceRepo: 'docker-remote'
    imageName: 'nginx'
