resources:
  containers:
  - container: nginx
    image: nginx
pool:
  vmImage: 'ubuntu-16.04'
container: sanjeev_container
services:
  nginx: nginx
steps:
- task: ArtifactoryDocker@1
  inputs:
    command: 'pull'
    artifactoryService: 'Support'
    sourceRepo: 'docker-remote'
    imageName: 'nginx'